version: 2
jobs:
  build:
    docker:
      - image: cimg/go:latest

    working_directory: ~/osman
    steps:
      - checkout
      - run: |
          export PATH="$HOME/osman/bin:$PATH"
          osman dev/lint dev/test build
workflows:
  version: 2
  pull-request:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
