name: ci

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: CI
        run: |
          go build -O ./bin/tmp-build
          ./bin/tmp-build dev/lint dev/test build
