name: release

on:
  release:
    types: [created]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/github-script@v6
        name: Extract tag name
        id: tag
        with:
          result-encoding: string
          script: return context.ref.replace(/refs\/tags\//, '');
      - run: |
          curl https://raw.githubusercontent.com/outofforest/build/main/build > /tmp/outofforest-build
          chmod u+x /tmp/outofforest-build
          /tmp/outofforest-build . build
        name: Build OSMan
      - uses: outofforest/rpmbuild@main
        name: Build RPM
        id: rpm
        with:
          spec_file: ./build/osman.spec
          version: ${{ steps.tag.outputs.result }}
          out_dir: ./release
      - uses: svenstaro/upload-release-action@v2
        name: Upload RPM package to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{ steps.rpm.outputs.rpm_path }}
